In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

In [30]:
# import data
data = pd.read_csv('data/us_acs_qf_clean.csv')

In [32]:
# clean data
# remove index column since it doesn't provide valuable info
data = data.drop(["place_id"], axis = 1)
# remove state_id for IL dataset
# data = data.drop(["state_id"], axis = 1)

# REMOVE NULL / BAD DATA

# remove city names for scaling
locations = data["Name"]
data = data.drop(["Name"], axis=1)


In [33]:
# standardize data
scaler = StandardScaler()
scaler.fit(data)
scaled_data = pd.DataFrame(scaler.transform(data), columns = data.columns)

In [35]:
scaled_data

state_id  Total Population  Median Household Income  Per capita income  \
0     -1.894763         -0.112362                -0.897897          -0.565466   
1     -1.894763         -0.086106                -0.600046          -0.722889   
2     -1.894763         -0.131096                -0.669607          -0.468332   
3     -1.894763          0.265015                 0.598056           0.212832   
4     -1.894763          0.132331                -0.419899          -0.539087   
...         ...               ...                      ...                ...   
21330  1.758694         -0.127017                -0.147769           0.042862   
21331  1.758694         -0.096047                -0.190347           0.086380   
21332  1.758694         -0.122425                 1.713913           1.807866   
21333  1.758694         -0.080465                 0.003842          -0.188681   
21334  1.758694         -0.118188                 0.598185           0.018196   

       Under 5yo %  Under 18yo %  Over 65yo %  Female %   White %  \
0        -0.955067     -1.052584    -0.085594 -0.601737 -1.367759   
1        -0.157268     -0.134881    -0.067873  1.070031 -2.086376   
2         1.238880      0.220359    -0.138496 -0.009212  0.762966   
3         0.175148      0.457186     0.200440  0.329374 -0.503408   
4         0.640531      1.286079     0.117456  0.414021  0.345866   
...            ...           ...          ...       ...       ...   
21330     0.042182     -0.756551    -0.129246  0.540991  0.652409   
21331    -0.522926     -1.111790    -0.083778 -0.368959  0.657434   
21332    -0.722375     -1.126592    -0.115156 -0.813353  0.762966   
21333     0.441081      0.190756    -0.061995 -0.538252  0.149880   
21334    -0.323476     -0.430914    -0.142818  0.223566  0.657434   

       Black or African American %  ...  \
0                         1.795688  ...   
1                         3.037641  ...   
2                        -0.555583  ...   
3                         0.607994  ...   
4                        -0.326485  ...   
...                            ...  ...   
21330                    -0.290312  ...   
21331                    -0.549555  ...   
21332                    -0.555583  ...   
21333                    -0.495294  ...   
21334                    -0.435005  ...   

       Language other than English spoken at home %  \
0                                         -0.510098   
1                                         -0.709103   
2                                         -0.683425   
3                                         -0.182703   
4                                          1.171814   
...                                             ...   
21330                                     -0.721942   
21331                                      0.401473   
21332                                     -0.542195   
21333                                     -0.092830   
21334                                      0.504185   

       Households with computer %  Households with internet %  \
0                       -0.326341                    0.066771   
1                       -0.869986                   -1.520285   
2                       -0.242704                   -0.019796   
3                        0.914285                    0.999767   
4                        0.119727                    0.595789   
...                           ...                         ...   
21330                   -0.939685                   -0.519959   
21331                   -1.120900                   -0.895082   
21332                    1.360353                    0.961293   
21333                    0.077908                    0.124482   
21334                    1.193077                    0.903582   

       High school graduate or higher %  Bachelor's degree or higher %  \
0                             -1.402390                      -0.443134   
1                             -1.473490                      -0.670283   
2                       

In [59]:
nbrs = NearestNeighbors(n_neighbors=100,
                        algorithm="ball_tree").fit(scaled_data)
distances, indices = nbrs.kneighbors(scaled_data)

In [58]:
indices
# put array into json file for 100 nearest


array([[    0,   112,    61, ...,   232,   889,   212],
       [    1,   215,  3580, ...,   212,    35,  7653],
       [    2,  4429,   199, ...,  6248,  5972,  5383],
       ...,
       [21332, 20062, 19224, ..., 20247, 21025, 14038],
       [21333, 21272, 21185, ..., 20839, 17622, 20798],
       [21334, 19006, 18512, ..., 18430, 18531, 18405]], dtype=int64)

In [51]:
distances

array([[0.        , 2.68312244, 2.91421347, ..., 3.16182159, 3.22040316,
        3.23005466],
       [0.        , 2.19110475, 2.56498223, ..., 2.67198454, 2.69588621,
        2.70549397],
       [0.        , 2.15637349, 2.173133  , ..., 2.25030916, 2.25032594,
        2.26454615],
       ...,
       [0.        , 2.91093666, 3.01642761, ..., 3.55629187, 3.55814283,
        3.56944774],
       [0.        , 1.94301892, 1.99892398, ..., 2.19722258, 2.2301207 ,
        2.23536946],
       [0.        , 3.20842815, 3.41643293, ..., 3.97400034, 3.99877654,
        4.0130001 ]])

In [56]:
for i in indices[4634]:
    print(locations[i])

Evanston city, Illinois
West Hartford CDP, Connecticut
Sandy Springs city, Georgia
Towson CDP, Maryland
Wheaton city, Illinois
Arlington Heights village, Illinois
Oak Park village, Illinois
Columbia CDP, Maryland
Farmington Hills city, Michigan
Dunwoody city, Georgia


In [39]:
locations

0          Abbeville city, Alabama
1         Adamsville city, Alabama
2            Addison town, Alabama
3          Alabaster city, Alabama
4        Albertville city, Alabama
                   ...            
21330          Upton town, Wyoming
21331      Wheatland town, Wyoming
21332          Wilson CDP, Wyoming
21333        Worland city, Wyoming
21334         Wright town, Wyoming
Name: Name, Length: 21335, dtype: object

In [53]:
query = locations.str.contains("Evanston")
query.index[query]

Int64Index([4634, 21277], dtype='int64')

In [55]:
locations[4634]

'Evanston city, Illinois'

In [60]:
import json

In [63]:
indices

array([[    0,   112,    61, ..., 10238,   787,  3474],
       [    1,   215,  3580, ...,  7715,  3952,  3695],
       [    2,  4429,   199, ...,  8756,  6749,   881],
       ...,
       [21332, 20062, 19224, ...,  8505, 12433, 20143],
       [21333, 21272, 21185, ..., 14870, 18599, 17588],
       [21334, 19006, 18512, ..., 13341, 17354, 19246]], dtype=int64)

In [64]:
with open("100nn_cities.json", 'w') as file:
    json.dump(indices.tolist(), file)